name: fitnest
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc:
  cupertino_icons: ^0.1.3
  equatable:
  flutter_bloc:
  flutter_custom_tabs:
  flutter_svg: ^0.18.0
  google_sign_in:
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  http:
  intl:
  progressive_image:
  path_provider:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  hive_generator: ^0.7.1
  build_runner: ^1.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat_Regular.ttf
        - asset: assets/fonts/Montserrat_Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat_Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat_ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat_Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat_Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat_ExtraLight.ttf
          weight: 200
